<?php


namespace serviceBundle\Repository;
use MyBundle\Entity\Service;
use Doctrine\ORM\Query;
/**
 * serviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEntitiesByString($str)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT s
        FROM MyBundle:Service s
        WHERE s.description LIKE :str'

            )->setParameter('str', '%'.$str.'%')->getResult();
    }
    public function findCommande($user)
    {
        $query=$this->getEntityManager()
            ->createQuery("select s from MyBundle:Service s WHERE s.idUser='$user'");
        return $query->getResult();
    }
}
