<?php

namespace MyBundle\Repository;

/**
 * attestationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class attestationRepository extends \Doctrine\ORM\EntityRepository
{
}
